# Generated by Django 5.0.2 on 2024-06-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Users',
        ),
    ]
